# Generated by Django 5.0.4 on 2024-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
