# Generated by Django 5.0.4 on 2024-04-22 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userprofile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='participate',
        ),
        migrations.AddField(
            model_name='group',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(default='logo.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
